### PR TITLE
Disabling infinite traces due to their inability to complete; the valid trace duration range now goes from 1 second to 2147483647 seconds

### LINKED ISSUE #334: Trace endpoint should not allow indefinite durations
Alternatively, we should stop collecting gracefully during cancellations if duration is -1, so as to make the nettrace file usable.

### PR DESCRIPTION
**Pull request by kkeirstead**
Trace files cannot be opened when terminated before completion. As a result, traces that run indefinitely will never be accessible to users. The new range allows traces to run between 1 second and a signed integer's max value (equating roughly to 68 years). 

Closes #334

### CODE REVIEW

**Comment by jander-msft** [comment]
While I agree with the sentiment that specifying an infinite duration does not allow for a complete nettrace file, I'm not convinced that removing this ability is the correct thing to do. For example, it might be possible to take the content stream of the /trace response with an infinite duration and pass it into an EventPipeEventSource for dynamic observability of interesting events (this is something we should test). Another possibility is that if the process shuts down gracefully, then the session will be completed correctly, but I'm not certain (maybe @josalem may know) and not sure if we should give this scenario much weight.

I'm thinking that we should document that an infinite duration will not yield a valid nettrace file (due to cancellation) and leave the functionality as-is if the response stream is usable for on-demand observation.

@shirhatti, @wiktork what do you think?

**Comment by shirhatti** [comment]
> I'm thinking that we should document that an infinite duration will not yield a valid nettrace file (due to cancellation) and leave the functionality as-is if the response stream is usable for on-demand observation.

Agreed on not changing dotnet-monitor

I view that as a limitation of the tooling. The format is pretty resilient and we should be able to parse out everything except the last incomplete block.

The way I'd solve it, is add API to TraceEvent to allow parsing incomplete nettrace files 😄

@noahfalk for his thoughts?

**Comment by shirhatti** [comment]
@josalem I was just looking at `dotnet trace convert` and if I'm not mistaken we already can handle incomplete nettraces?

**Comment by josalem** [comment]
It'll handle incomplete traces but doesn't guarantee you have all the information needed to symbolize in those cases. A truncated trace most likely does not have rundown in it which makes symbolization difficult.

**Comment by noahfalk** [comment]
> I view that as a limitation of the tooling. The format is pretty resilient and we should be able to parse out everything except the last incomplete block.

> The way I'd solve it, is add API to TraceEvent to allow parsing incomplete nettrace files 😄

👍 Agreed

> It'll handle incomplete traces but doesn't guarantee you have all the information needed to symbolize in those cases. A truncated trace most likely does not have rundown in it which makes symbolization difficult.

This is certainly a scenario limitation, at least for now. In the future (.NET 7?) I hope we can support emitting the symbols on demand rather than waiting for rundown to eliminate this issue.

**Comment by wiktork** [comment]
We may need to do something better with VS handling partial .nettrace files too. Right now VS silently fails to load partial files.

Note that if we implement a rolling egress provider, such as with https://github.com/dotnet/dotnet-monitor/issues/85, this experience would be much better.

**Pull request closed without merging**
