### PR TITLE
Use federated connections for storage account and apiscan access

### PR DESCRIPTION
**Pull request by mmitche**

### CODE REVIEW

**Comment by mmitche** [comment]
@jander-msft Can you help with verifying this and backporting? Already launched a compliance pipeline run: https://dev.azure.com/dnceng/internal/_build/results?buildId=2482288&view=results.

Other notes:
- dotnetstage account keys are going away at some point in the near future.
- Same with the dotnetbuilds variable group, so you will need to backport these changes to older in-support releases.

**Comment by mmitche** [comment]
compliance run is working fine with APISCan. I'm going to remove the variable group after this merges.

**Comment by jander-msft** [comment]
This appears to not work on the Linux build legs e.g. https://dev.azure.com/dnceng/internal/_build/results?buildId=2482363&view=logs&j=5cee8dfe-76ad-5548-6fb0-db50ffe1c51d&t=a11a0513-7a7e-527c-a490-2b9da3b9540e

I believe the difference is that the Linux build legs are containerized and the container images do not contain pwsh on them.

**Comment by mmitche** [comment]
Cool I'll resolve that before checking this in.

**Comment by mmitche** [comment]
@jander-msft https://dev.azure.com/dnceng/internal/_build/results?buildId=2486275 looking good now, aside from the unrelated Microbuild installation issue

**Review by jander-msft — APPROVED** [review]

**Pull request merged**
