### PR TITLE
[NO REVIEW, NO MERGE] Investigating test timeouts

### PR DESCRIPTION
**Pull request by jander-msft**

### CODE REVIEW

**Comment by WeihanLi** [comment]
Maybe we could mark this as draft so that it will not be merged by mistake

**Comment by jander-msft** [comment]
My current theory is that this is an HttpClient socket exhaustion problem. Thinking of trying a Xunit collection fixture to set up an IHttpClientFactory that is shared among all of the tests.

**Comment by WeihanLi** [comment]
> My current theory is that this is an HttpClient socket exhaustion problem. Thinking of trying a Xunit collection fixture to set up an IHttpClientFactory that is shared among all of the tests.

We wanna make the `ApiClient` singleton, right?
Maybe we can try this xunit dependency injection extension, that will make the test code much more clean than collection fixture I think, maybe you wanna have a look at the project <https://github.com/pengweiqhca/Xunit.DependencyInjection>

**Pull request closed without merging**
