### PR TITLE
Replace redundant LiveJwtBearerHandler with standard JwtBearerHandler

### PR DESCRIPTION
**Pull request by RomanBats**
Closes https://github.com/dotnet/dotnet-monitor/issues/2152.

IOptionsMonitor<JwtBearerOptions> looks to be a singleton, LiveJwtBearerHandler, on the other hand, is a transient service.
The Handler is initialized per each request thus ctor is called and a new OnChange event handler is added to an IOptionsMonitor<JwtBearerOptions>. OnChange event handlers are never garbage collected and are stored in the IOptionMonitor together with captured parameters (a disposed instance of HttpContext). 

And the side effect of this implementation is not only memory leak but, in case the API was running for a couple of days and was constantly called by the Prometheus to scrape metrics, after configurations are changed, all event handlers (registered with OnChange for each Prometheus call) will be invoked (which in my case 1440 times for each day of being live).

I think LiveJwtBearerHandler is redundant since the InitializeAsync method of AuthenticationHandler<TOptions> is called with every request and the latest Options is being obtained:
image

I have tested it by changing MonitorApiKey configurations and with every subsequent request, a different bearer token should be provided for an API call to be authenticated, which I assume is the end goal of LiveJwtBearerHandler.

### CODE REVIEW

**Comment by RomanBats** [comment]
@kelltrick

**Comment by jander-msft** [comment]
> I think LiveJwtBearerHandler is redundant since the InitializeAsync method of AuthenticationHandler is called with every request and the latest Options is being obtained

That was my understanding too back when this was introduced and looking through the ASP.NET code that uses this says this should be transient.

**Review by jander-msft — APPROVED** [review]

**Pull request merged**
